#!/usr/bin/env python
# _*_coding: utf8_*_
import MySQLdb
from MySQLdb import cursors
import threading

slaveList = [
             'ip list'
             ]
def getSlaveTime(host):
    try:
        username = 'username'
        passwd = 'password'
        conn = MySQLdb.connect(user = username, passwd = passwd,  host = host, connect_timeout = 5, cursorclass = cursors.DictCursor)
        cur = conn.cursor()
        cur.execute('''show slave status''')
        fallSec = cur.fetchone()['Seconds_Behind_Master']
        cur.close()
        conn.close()
        print  host + ' 落后 ' + str(fallSec)
    except:
        print host + ' 落后 ' + str(10000000)
   
for host in slaveList:
    s = threading.Thread(target = getSlaveTime,args = (host,))
    s.start()
